mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
    MONGO_DATA_DIR: /data/db
    MONGO_LOG_DIR: /data/log
    MONGODB_USER: mongouser
    MONGODB_PASS: mongouser
  volumes:
    - /data/db:/data/db
  ports:
    - 27017:27017
  restart: always